#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	need net
	use dns
	after apache2
}

start() {
	ebegin "Starting bitten-slave"
	start-stop-daemon --start --quiet --background \
		--make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -- ${DAEMON_ARGS}
	eend $?
}

stop() {
	ebegin "Stopping bitten-slave"
	start-stop-daemon --stop --quiet --pidfile ${PIDFILE} --retry 5
	eend $?
}
